package com.pivovarit.movies.domain;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.Year;
import java.util.Collection;
import java.util.Optional;
import java.util.stream.StreamSupport;

@Repository
public interface MovieAutogeneratedRepository extends JpaRepository<MoviePersistence, MovieIdPersistence> {
    Optional<MoviePersistence> findByTitle(String title);
    Collection<MoviePersistence> findAllByType(MovieType type);
    Collection<MoviePersistence> findAllByYear(Year year);

    Collection<MoviePersistence> findAllByYearLessThan(Year year);

    Collection<MoviePersistence> findAllByYearBetweenOrderByYearDesc(Year yearStart, Year yearEnd);
}
