package com.pivovarit.movies.domain;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.Year;
import java.util.Collection;
import java.util.Optional;

@Repository
public interface MovieAutogeneratedRepository extends JpaRepository<MoviePersistence, MovieIdPersistence> {
    Optional<MoviePersistence> findByTitle(String title);
    Collection<Movie> findAllByType(MovieType type);
    Collection<Movie> findAllByYear(Year year);
}
